sudo: false

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
on:
  branch: master

deploy:
  provider: heroku
  api_key:
    secure: f0d5ac77-9801-4b20-8138-d434dc8e6fd6
